### ISSUE TITLE
sendSMSSchema is too strict

### ISSUE THREAD

**Issue by rezamfebrian** [RingRing-cloud/MessageApiClient-NodeJS#19]
**Describe the issue**
The current sendSMSSchema.json only let phone numbers with exactly 11 digits to be allowed. This is far too strict for European phone numbers.

**Expected behavior**
The schema should cover a larger portion of possible phone numbers. For example, in our database all of the phone numbers are between 9-15 digits. I'm not so sure how the schema looks like internationally.

**Comment by RingRing-cloud** [comment]
updated in commit https://github.com/RingRing-cloud/MessageApiClient-NodeJS/commit/c0b9c3fa6624db0ed081822ccd6c6d85571d20c5
